### ISSUE TITLE
Setup and automate splunk log aggregation

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1036]
- [x] Ensure all emory servers send their logs to splunk
- [x] automate this setup

NOTE: this is only the server / forwarder ansible setup on the server.  We'll set up a separate ticket for adding particular log files to the spunk instance using spunk tools.

**Comment by mark-dce** [comment]
@bess Is this ticket done, or can we get it to done quickly?  It looks like I'm seeing
* etd.library.emory.edu
* prod-fedora.library.emory.edu
* prod-solr.library.emory.edu	
* qa-fedora.library.emory.edu
* qa-solr.library.emory.edu
* qa-upgrade-etd 
* staging-upgrade-etd
* upgrade-etd

It looks like we're missing
* qa-apache.library.emory.edu 18.220.159.157
* staging-apache.library.emory.edu 18.220.209.96
* staging-fedora.library.emory.edu 52.15.88.202
* staging-solr.library.emory.edu 13.59.154.114

Since we 1) have been running without the missing servers in spunk for almost a year, and 2) plan to decommission those servers shortly when we deploy the new builds, I would be happy to consider this ticket closed unless there's some other work that I'm not aware of.  If there is other work that needs to be done, let's add it to the acceptance criteria at top; otherwise, let's close the ticket.
