### ISSUE TITLE
Fix Lift Embargo

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1108]
See Hyrax ticket https://github.com/samvera/hyrax/issues/3058

Consider using the term "Lift Embargo" instead of deactivate which seems ambiguous: deactivate=delete (keep at restricted level) OR deactivate=lift(set to less restrictive level)

Clearest would be buttons that say "Set to X now" where X = the end embargo state

**Comment by no-reply** [comment]
This turns out to be more complex than anticipated. "Deactivate" does a couple of different things, depending on the current permissions, release date, and calendar date when the button is pushed. It is also included in the UI in other places ("Expired Active Embargos"/"Deactivated Embargos"), and any changes to its behavior need to be cleaned up there.

The fix we have in mind for this ticket is:

  - [ ] Remove "Deactivate Embargo" button from the embargo edit view;
  - [ ] Change "Deactivate" to "Release" in the embargos index view;
  - [ ] Document relevant issues in #3058, and reopen design discussions for embargo management there.

**Comment by mark-dce** [comment]
Per discussion 6/21 - let's remove the "Deactivate" button from the individual embargo management page, and change the wording to "release embargo" on the expired embargo page.

**Comment by mark-dce** [comment]
sorry for duplicate info - my version of the ticket didn't pick up no-reply's comments until after I added the comment.
