### ISSUE TITLE
Review submissions "Published" list doesn't make sense

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1166]
**STEPS TO REPRODUCE**
1. Login as an administrator
1. Navigate to the dashboard
1. Click on "Review Submissions"
1. Click on the "Published" tab

**EXPECTED BEHAVIOR**
I should see all the works that are in the "published" workflow state

**ACTUAL BEHAVIOR**
I see a set of works that seem to be randomly selected. At time of writing there are 104 objects in a `published` workflow state, but only 7 objects on that screen. 

**EXAMPLE**
Login as tezproxy  
https://qa-upgrade-etd.emory.edu/admin/workflows?locale=en#published  
vs.   
The "Repository Objects" count at the bottom of https://qa-upgrade-etd.emory.edu/dashboard?locale=en

**Comment by bess** [comment]
I've entered this as a bug in Hyrax: https://github.com/samvera/hyrax/issues/3171

I spent a couple of days on this and can't figure it out. I believe it's a bug in how the query is happening -- instead of querying for ALL published items, it seems to be getting only objects that are `published` within a specific workflow. I believe the problem is a function of the number of admin sets and workflow roles we have. 

Instead of pursuing this further, @mark-dce and I agreed to remove the `Review Submissions` menu item from the admin dashboard. Repository Content --> Works --> All Works serves the same function and behaves as expected.
