### ISSUE TITLE
Shutdown & startup services in graceful order

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1261]
**ISSUE**
When we shutdown or start up the system, Honeybadger is reporting a variety of connection related errors until all dependent services have launched and are running successfully.

**ACCEPTANCE**
- [ ] ~Stop Honeybadger before any other services~
- [ ] ~Start Honeybadger after all other dependency services (Solr, Redis, Postgres, etc.)~
- [x] [BONUS] Stop other services in a graceful order (eg. Passenger before Redis, etc.)
- [x] [BONUS] Start other services in a graceful order (eg. Solr before Apache, etc.)
- [x] Once this change is in ansible-samvera, run the relevant ansible roles on all DCE systems so we stop getting these errors

**Comment by bess** [comment]
We can't actually turn honeybadger off, because it's just part of an apache / passenger application. What we can do instead, however, is ensure that all apache's pre-requisites are loaded before it comes up (and that during shutdown, apache2 goes down before its pre-requisites) and this should eliminate this subset of honeybadger errors.

**Comment by bess** [comment]
PR here: https://github.com/curationexperts/dce-cm/pull/49
