### ISSUE TITLE
Double Majors

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#134]
The current system doesn't manage Dual Major without developer intervention. Is this just because the student is submitting two ETDs under different programs?

**Comment by bnash108** [comment]
We discussed this in our call today, but I'll provide a recap here. 

Super user and Developer intervention is needed if a student is going to submit 2 theses or a thesis + dissertation (i.e. they will have two separate records in the same semester) because the current application wasn't built for this use case. Ideally, the new app would handle this better.
Super user and Developer intervention is NOT needed if the dual degree student is only submitted 1 thesis/dissertation. The student can change their school/program/department if needed in the application to reflect which degree they are submitting a thesis/dissertation for.

**Comment by shanitajohn** [comment]
Great. Opening a ticket to create a Dual Major workflow, will copy notes there and close this ticket.
