### ISSUE TITLE
Will Keywords be auto suggested from a config file?

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#144]
Determine if keywords will be autosuggested from a config file or if this is just a free-form text field.

**Comment by mark-dce** [comment]
There is no algorithmic means to extract existing keywords and remove entries that "shouldn't" be autosuggested.  The key consideration here is wether Emory staff will have time to create an initial list and periodically groom the list on a quarterly, annual, or bi-annual basis.  If keeping a keyword list groomed is not feasible, we should not attempt to autosuggest since we have no good list to provide suggestions from.

**Comment by fpici** [comment]
I think we have come to an agreement that we do not want to maintain a keyword list nor do we want to auto-suggest from keywords already created. so, I believe the consensus is to have the keywords be a free-form text field . Hope this helps!
