### ISSUE TITLE
Allow students to easily replace their Primary PDF

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1445]
**STORY**
As a student, when my school approver "Requests Changes" from me involving my primary PDF or supplemental files, I should be able to:

**ACCEPTANCE CRITERIA**
- [x] Delete and replace my primary PDF and resubmit my ETD for review 
- [x] Delete and replace any one of my supplemental files (without affecting the others) and resubmit my ETD for review 
- [ ] ~~Edit the required metadata for any one of my supplemental files (without affecting the others) and resubmit my ETD for review~~
- [x] If I go into an already created ETD, I need to easily be able to replace my primary and supplementary files

**Comment by jenlindner** [comment]
I looked at what happens when you submit a new pdf to an existing etd and found that a new FileSet gets created and attached properly to the Etd, but it is not set to the Etd's representative_id or thumbnail properties. However, this could be done in the Etd's edit code. 

See https://github.com/samvera/hyrax/blob/2.1-stable/app/actors/hyrax/actors/file_set_actor.rb#L76-L78 for reference.

**Comment by val99erie** [comment]
After talking with Bess, we have cut this requirement from scope:
`Edit the required metadata for any one of my supplemental files (without affecting the others) and resubmit my ETD for review`

Neither hyrax no laevigata currently have this feature, so it would be entirely new work.  It's not likely to be commonly needed, and there are some work-arounds available.  (e.g. Add & remove the file to change the metadata, or edit the title from the FileSet edit form)
