### ISSUE TITLE
Attaching a file does not work in Safari

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1513]
- [ ] In the new UI attaching a file works in Chrome but not in Safari

**Comment by little9** [comment]
@bess I did an investigation of this this AM and it turns out that there is a bug in Safari 11 that is 
causing this behavior: https://bugs.webkit.org/show_bug.cgi?id=184490

I'm going to see what I can do to work around it. That's why this is only happening in Safari 11. I tested in an older version and it was working correctly.
