### ISSUE TITLE
Don't provide formatting options that aren't retained / displayed

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1540]
**STORY**
As a student, I don't want to find out that text I've carefully formatted in my submission wasn't retained, so that I've ended up wasting my time.

**DETAILS**
I went through and set a line of text using each of the formatting options provided in the submission form.  I've provided a screenshot of what gets displayed after I submit the work and when I go back to edit it.  It appears that much of the formatting is completely stripped.

**ACCEPTANCE**
- [ ] [PREFERRED] Don't strip formatting allowed in the submission form
OR
- [x] Don't provide formatting options that will not be retained when the ETD is displayed

<img width="804" alt="abstract and toc formatting" src="https://user-images.githubusercontent.com/3064318/43878048-aefde6c0-9b62-11e8-8feb-93a63f1bca91.png">

**Comment by little9** [comment]
@mark-dce none of the formatting is stripped out when doing the submission from the form. I was displaying the text without formatting on the Submit tab **but only for display**. Is the normalization process on the server removing the markup or does it only strip out white space?  If we didn't add some of these normalization rules, then there might be something in Hyrax that is doing additional normalization. 

This is a really tricky problem because if we allow all this through it could screw up the structure of the page. I'm leaning towards option 2 right now.

**Comment by mark-dce** [comment]
We should probably talk through this on an item by item basis.  It seems pretty important to provide numbers and indents for the Table of Contents.  It seems like some of the other options like reverse text are way less essential if we can remove them from the tool pallet.  Overall, we just don't want students to slave over perfecting the formatting of their submission only to find that it gets stripped out anyway.

**Comment by little9** [comment]
Addresses by Bess in #1621
