### ISSUE TITLE
Prep data for School / Department pull down menus

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#156]
- [ ] Parse the RDF program file into JSON and store the JSON
- [ ] Parse the JSON file such that:
  - [ ] We can get a list of all Departments in a School
  - [ ] We can get a list of all Programs in a Department
- [ ] Be able to drive a select menu from the parsed JSON

**Comment by mark-dce** [comment]
We should understand what the system of authority for this list ls.  Is there a system we could just request this data from directly instead of having someone in the Library recreate it?  If the reason it's being recreated is because the data needs to be transformed in some way before using it, how are we going to match information provided by Emory systems about the users?
