### ISSUE TITLE
Be able to remove a committee member

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1616]
- [x] When editing an ETD be able to remove a committee member or chair

**Comment by val99erie** [comment]
The solution that I implemented works properly from the point-of-view of a student, but it leaves behind orphaned records in fedora.  After discussion with the team, since we are so close to the deadline, we decided that this is acceptable for now.  I wrote story #1733 to fix this problem in a future release.

**Comment by RachelDCE** [comment]
Was able to edit both committee member and chair. 

Tested on QA | 2017 Emory University. Version v2.0.0-beta8 updated 22 August 2018
