### ISSUE TITLE
Use Emory appropriate "rights" options

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#162]
- [ ] Get the Emory appropriate "rights" from Bethany
- [ ] Update the "rights" from the pull down menu so they reflect Emory options

**Comment by fpici** [comment]
Hello there. 

Since the CC-Licenses dropdown seems to be a default within Hydra, we would like to have DCE build it (or drop it in) but don’t turn it on. We would like to have the option to roll it out but don’t want to make it public. This way we flip the switch on it later on when we decide to do so.
We also would like the licenses to be editable so we can have control over the features from 4.0 and newer. In other words, we want the option to add a 5.0 license, eliminate older versions of the license, and remove the Public Domain license. Hope this helps :-)

**Comment by bess** [comment]
@fpici What license should be recorded for the ETDs that are being deposited, given that there will be no option to choose a license? Do we just say "all rights reserved"?

**Comment by fpici** [comment]
Hi Bess. That is a good question. Unfortunately Bethany, Melanie, and Lisa are out this week and they would have the proper answer BUT for now the current text reads:

 "Permission granted by the author to include this thesis or dissertation in this repository. All rights reserved by the author. Please contact the author for information regarding the reproduction and use of this thesis or dissertation."

**Comment by shanitajohn** [comment]
Incorporate into Wireframe ticket

**Comment by lamacklin** [comment]
Fran's answer is correct.  All rights are reserved by the author (aka the student).
