### ISSUE TITLE
When editing Committee Chair & Member - edited chair/member persists and new is added

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/laevigata#1675]
When editing Committee Chair & Member:

I edit the Name field and instead of replacing/changing that name- a new chair/member is added, so that I end up with multiple unintentional chairs/members. New ones added each time I try to edit.

![screen shot 2018-08-17 at 3 33 33 pm](https://user-images.githubusercontent.com/23509160/44287576-ee026900-a232-11e8-9329-ba01b6e7c996.png)

Tested in QA | 2017 Emory University. Version master updated 17 August 2018

**Comment by val99erie** [comment]
The solution that I implemented works properly from the point-of-view of a student, but it leaves behind orphaned records in fedora.  After discussion with the team, since we are so close to the deadline, we decided that this is acceptable for now.  I wrote story #1733 to fix this problem in a future release.

**Comment by RachelDCE** [comment]
Was able to change and add committee chairs and members without unintended multiples showing. 

Tested on QA | 2017 Emory University. Version v2.0.0-beta8 updated 22 August 2018
