### ISSUE TITLE
Don't allow editing embargo request fields after graduation

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1728]
**ISSUE**
When I edit an embargoed ETD for a graduated student, the edit form makes it look like there is no embargo in place.

Server: https://qa-upgrade-etd.emory.edu/
Version v2.0.0-beta6 updated 21 August 2018.

**STEPS TO REPRODUCE**
1. Find an ETD under embargo - e.g. 1z40ks82j - Epidemiology of the First Zika Virus Outbreak in the United States Virgin Islands, 2016–2017
1. Login as an administrator
1. Go to the single item show page for the ETD 
https://qa-upgrade-etd.emory.edu/concern/etds/1z40ks82j?locale=en
1. Click the "Edit" button
1. Scroll down to the "Embargo" section of the edit form

**ACTUAL BEHAVIOR**
* The embargo length and content don't match the settings on the show view
* I can edit the Requested Length and Content to embargo

**DESIRED BEHAVIOR**
* Students - probably shouldn't be editing their ETD after graduation - but for safety we should display "This ETD is under embargo, please contact your department if you would like modify the embargo"
* Approvers & Admins - provide a link to the Embargo management page: "This EDT is under embargo, please use the [Embargo Management page](/embargoes) to modify the embargo settings."

**Comment by val99erie** [comment]
@mark-dce How much time do you want me to spend on this?  Since we're so close to the deadline, I assume you'd like a quick & easy solution, rather than spending lots of time on it.

Here are some things to consider:

- It's pretty easy for me to add some generic text to records where the student has already graduated.
- Adding conditional text based on whether the ETD is currently under embargo is more work.
- Adding conditional text and links depending on whether the user is a student or an admin is more work.

If I just wrote some simple, generic text like this, would that be enough?
.

<img width="1041" alt="embargo_section" src="https://user-images.githubusercontent.com/298865/44493003-0ce66e00-a62c-11e8-9382-9fe09751dd49.png">

**Comment by mark-dce** [comment]
Yes - the simple solution and that text works.  If it's easy to remove the paragraph above it "You have the option to restrict access to your thesis or dissertation for a limited time..." that would be awesome; otherwise, just replacing the drop downs with the static *please contact your department* text is great.

**Comment by mark-dce** [comment]
Confirmed fixed Version v2.0.1-beta1 updated 28 August 2018

<img width="1162" alt="1728 - disable changing embargo requests post graduations - fixed" src="https://user-images.githubusercontent.com/3064318/44803297-ac9f8100-ab83-11e8-9230-a496c2fa66b1.png">
