### ISSUE TITLE
Embargo Emails Cut Off Text

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#1859]
According to Fran (https://github.com/emory-libraries/etd-issues/issues/56#issuecomment-460243850), the embargo emails are not including the full message text (https://github.com/curationexperts/laevigata/blob/master/app/services/hyrax/workflow/seven_day_embargo_notification.rb)

**Comment by fpici** [comment]
Hi Bess.

Thank you for finding the root of this problem.

Whilst you are at it, I also see that the bottom of each message is generating this additional text:

“Visit https://etd.library.emory.edu/ and go to your inbox for more info.”

(See attached screenshot)

Since alum no longer have access to their Inbox, I think the message should say:

“Visit https://etd.library.emory.edu/ for more info.”

[cid:image001.png@01D4C514.85957790]

Hope this helps!


Frances Pici
Scholarly Repository Application Support Analyst
Scholarly Communications Office
Emory University LibrarIes and Information Technology
Robert W. Woodruff Library
540 Asbury Circle
Atlanta, GA 30322
404.727.7673
fpici@emory.edu<mailto:fpici@emory.edu>
