### ISSUE TITLE
Address low-risk omniauth security issue

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#1903]
Follow the breadcrumbs here https://github.com/curationexperts/laevigata/network/alert/Gemfile.lock/omniauth/open  

and here 
https://github.com/omniauth/omniauth/pull/809
https://github.com/omniauth/omniauth-rails/pull/1

Determine whether there is any action needed on our part.

**Comment by bess** [comment]
I took a swing at the omniauth security issue, but I don't think it's going to be a quick fix. See PR here: https://github.com/curationexperts/laevigata/pull/1907. 

This is not a new issue. It has been around since 2015, but a CVE was just issued for it, which is why it's suddenly on our radar. There will eventually be a better fix in place. I don't think we're particularly vulnerable, as first someone would have to compromise Emory's shibboleth server to take advantage of this. I recommend we wait until there is a straightforward fix available.

**Comment by mark-dce** [comment]
Exploiting this vulnerability would require someone to
1) breach emory's shibboleth system
2) have access to an active session still open in another users browser

We think the likelihood of that (and the corresponding risk if it every did happen) is sufficiently low that we're closing out this issue for now.
