### ISSUE TITLE
Test Box upload against Feb 2020 release of the code

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/laevigata#2001]
**Acceptance**

- [ ] Can't run the release  - or-
- [ ] Release runs and we can upload to Box -or-
- [x] Release runs and we can't upload to Box

**Comment by bess** [comment]
I brought up our backup from ETD production from 21 Feb, which was validated at the time to work with box.com. I can run the release fine, and it doesn't have the updated SSL certs (just in case that was an issue). Same behavior as current production for box.com:

1. Sign in to box.com appears to succeed
2. Then it takes me back to my application without actually letting me into box.com
3. There are no log traces on our system (afaict) I suspect because the auth is happening on box.com's side of things.
