### ISSUE TITLE
Investigate ETD Outage 10/24/2020 07:51:03 AM

### ISSUE THREAD

**Issue by RachelDCE** [curationexperts/laevigata#2066]
Outage reported - See:
https://my.pingdom.com/app/reports/uptime#check=4537872

 Compare Pingdom, Nagios, and Splunk reporting for the outage period
 Identify any discrepancies
- [x] Dig deeper on any differences
- [ ] Provide evidence if we think the issue was with Pingdom or AWS

**Comment by mark-dce** [comment]
It appears that the service that routes requests to the application (i.e. the "Passenger" service) experienced an out of memory error starting at 7:51am Eastern that caused it to be unable to spawn new processes to respond to new incoming user requests.  The out of memory condition continued until 7:53am when Passenger restarted itself automatically to clear the memory leak.

![image](https://user-images.githubusercontent.com/3064318/97728641-cb6d6b00-1a9f-11eb-9d2f-1f56a2aa0c99.png)

The memory issue may be related to the system unsuccessfully retrying to create derivatives for a PDF at about the same time.

![image](https://user-images.githubusercontent.com/3064318/97730451-daedb380-1aa1-11eb-8ed8-87c00b17e92e.png)


Normally the system is able to recover from memory issues without needing to restart any services and this is the only time in the last 30 days we see this particular error condition causing a restart.  This is most likely due to exceptional memory demand caused by the failing PDF job at precisely the same time as new Passenger sessions were trying to spawn.  We'll keep an eye out for any repeats of this pattern, but don't anticipate them based on the relatively low likelihood of exactly this chain of events reoccurring in the timeframe necessary to trigger a restart of the passenger service.

![image](https://user-images.githubusercontent.com/3064318/97730141-7e8a9400-1aa1-11eb-8c57-6acbfe3079eb.png)

**Comment by mark-dce** [comment]
ROOT CAUSE ANALYSIS: the system experienced a low memory issue at the time of the outage, but was not able to clear and reallocate memory because of memory intensive PDF conversions that were occurring on the system at the same time.  The passenger service restarted itself as expected.  We've looked for evidence of this specific sequence of events re-occurring and don't see evidence of the issue reoccurring at any time in the last 30 days.

We have capture the logging extracts above as a baseline in case we see this problem re-occur in the future.

**Comment by mark-dce** [comment]
Also pasting the original Pingdom outage for reference:

![image](https://user-images.githubusercontent.com/3064318/97731417-13da5800-1aa3-11eb-85d8-43e3cb6bce41.png)
