### ISSUE TITLE
Allow user to save for later editing

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#213]
- [x] Save status of submission while student is editing
- [x] If they leave the application and come back later, prompt them to continue their work in progress
- [x] Student can keep editing their ETD as many times as they want until they are ready to submit the ETD to approver.

**Comment by shanitajohn** [comment]
@bess Is this different that the multi-save functionality @jenlindner is working on? If not, I'd like to absorb the acceptance criteria and close this ticket.  LMK.

**Comment by val99erie** [comment]
One possible way to implement this would be to add a 'draft' workflow state so that the student always has ability to edit their ETD until they are finally ready to submit it for approval.  We could probably just add a big 'Save my Draft' button under the checklist that saves the ETD but doesn't advance the workflow to the approver.

**Comment by mark-dce** [comment]
Handled as part of the User Interface work in Laevigata v2.0.0 👍
