### ISSUE TITLE
Hiding additional metadata on supplemental files erases data

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#683]

**Comment by jenlindner** [comment]
@shanitajohn this was actually a decision I made, because it makes validating the form and keeping the file list in sync with the metadata table much easier. 

In order to preserve the data in the metadata rows, when users click show, the code would need to check the file list and the metadata table and add new blank metadata rows for new files, or remove them if their corresponding files have been removed. I could change it, I can understand why a user might expect their data to remain if they click hide and then show again, but it's not a tiny thing. And I didn't want you to think I just missed this use case when I was writing it.

**Comment by shanitajohn** [comment]
@jenlindner Thank you for replying! I appreciate the explanation and understand that there is a lot of  work involved with fixing this. That being the case, I would strongly recommend we disable "hiding" the supplemental file metadata altogether, because we're not  "hiding" it. From the user's perspective, we're clearing/erasing it and that's a really frustrating experience;  to think you're completing one action and the result is another action entirely. Can you scope out how much work it would be to do the following, please? : 
- [ ] On the Show Additional Metadata button change "Show" to "Add" 
- [ ] Disable the ability to "hide" or collapse the  additional fields
- [ ] The copy on the "Add Additional Metadata" button should not change
