### ISSUE TITLE
Determine if db:seed is safe every deploy

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#689]
**ISSUE**
`bundle exec rake db:seed` is being run as part of every deployment.  Database seeding is usually something you only want done once when a new environment is initialized.  Is there any risk in us running this every time?  It's also the longest single operation in the deployment and would be attractive to remove for that reason too.

**ACCEPTANCE**
- [ ] Move database seeding from Capistrano to a task run by Ansible after the first-time deployment
*OR*
- [ ] Have the seed command check for expected configuration (e.g. some known workflow exists) and NOOP if the database appears to already have expected data
*OR*
- [x] Determine there's no harm in running the seed multiple times and leave AS-IS

**Comment by bess** [comment]
@mark-dce:

The only harm I see in running the seed multiple times is that it takes a long time. It is a pain, I know. 

Of your options, #1 won't work, because it needs to run not only on the first deploy, but also whenever a configuration file changes. We are already doing #2 as much as we can -- it does not re-create any AdminSets that exist already, but there is no way to check whether a change has been made to the workflow other than re-loading the workflow.

We could instead run it only on an as-needed basis, which would be:
* the first time the system is deployed
* after any change is made to the workflows
* after any change is made to the user configuration files (e.g., a superuser is added, a school approver is added)

Here are some options:

1. Remove the db:seed from capistrano for now, while we're doing lots of deploys but not making any changes to the workflow or user configuration files, and then add it back when we get to a point where deploys are less frequent and long running times will be less noticeable. 

2. Document that it needs to be run whenever those configuration files are changed. I think things have settled down enough that we aren't making changes to the workflows, so that would really only be when new users are added, if Emory staff find themselves unable to use the GUI to add approvers (the GUI is pretty clunky, so this might be a real use case). 

3. Leave things as-is.
