### ISSUE TITLE
Disable form tabs, display form as one single page

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#763]
**ACCEPTANCE CRITERIA**
- [ ] There should only be one tab with all of the content 
- [ ] There should be one "submit" button at the bottom of this page

**NOTES**
Do this in prerequisite for working on ticket #638

**Comment by val99erie** [comment]
The goal is to figure out if we can submit the form with javascript disabled and have all the data saved properly so that it all shows up in the edit form again.

**Comment by shanitajohn** [comment]
**EXAMPLE** 
All form divs set to "tab content active" 

![onepage-etdform.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46e79a9f338384acc2ecab47a252e2996b0a65633b0ba92e7391a172fd1723050c5748ab145f0910afad8e2ba6b76d248d5a5fe5877f4366846c4ff8e7df46f554f832815d84beb68b49c0ef3c27ef8b87473f17010ac4.png)

**Comment by mark-dce** [comment]
@val99erie - if it doesn't work to turn all javascript off (which might be hard because of fields that can have multiple values, etc. )  I think the thing I was looking for is whether we can render the form as one long form instead of having the hidden divs managed by javascript (as in Shanita's screenshot above).  I'm not sure if that helps solve the problem from a technical standpoint, but I'm hoping it at least makes it easier to visualize and talk about what fields are working and which aren't.

**Comment by val99erie** [comment]
@mark-dce and @shanitajohn : Could you confirm that the problem that you are trying to solve is that when the user tries to edit an existing ETD, the form is marked as 'invalid' and the user can't easily re-submit?  (This story describes a solution rather than the problem, so I want to make sure I'm working on the correct problem.)

**Comment by mark-dce** [comment]
This story is not meant to solve a user facing issue.  This is just to make it easier to see and comprehend the overall form contents and field re-population behaviors as we deal with individual field issues related to the form.

e.g.  If you unfold the form in this way, it becomes clearer that we ask for "School" in both the "About My Program" and "Embargos" section and would need to keep these synchronized in some way if we keep the two.  A better solution would be to have a single entry point for "School" on the form.
