### ISSUE TITLE
Supplemental files uploaded from Box might not be getting processed

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/laevigata#810]
I created a test ETD as tezprox with a local pdf and several supplemental files uploaded from Box, in Firefox. One of the supplemental files was the same pdf as the primary pdf, and the others were a tiff and two pngs. 

On the show view for the new EDT, the file icon is served in place of the processed files' thumbnails for all of the supplemental files except the pdf. 

https://qa-etd.library.emory.edu/concern/etds/nv9352841?locale=en

**Comment by bess** [comment]
These were failing in the background with the error `unknown attribute 'password' for User`. There seems to be a new expectation in Hyrax 1.0.5 that it should be able to run a method called `    find_or_create_system_user(user_key)` to create system users for running batch jobs and audits. This was failing for us, because we use shibboleth and our users don't have passwords.
