### ISSUE TITLE
submitting a blank comment results in an error

### ISSUE THREAD

**Issue by bess** [curationexperts/laevigata#915]
It appears that attempting to submit a blank comment results in an error.

## Error
[laevigata - prod/production] PowerConverter::ConversionError: Unable to convert false to 'sipity_action' (scope: #<Sipity::Workflow id: 28, name: "emory_one_step_approval", label: "One-step approval tailored for Emory", description: "A single-step workflow for mediated deposit in whi...", created_at: "2017-08-18 02:58:57", updated_at: "2017-08-18 02:59:02", permission_template_id: 10, active: true, allows_access_grant: false>).

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54219/faults/35548705)

**Comment by mark-dce** [comment]
Tested and fixed in Hyrax 2.1.  It's no longer possible to add a blank comment - i.e. choosing "Comment" from under "Review & Approval" options without entering a comment does not save anything or trigger any error.

https://qa-upgrade-etd.emory.edu/concern/etds/9p290946m?locale=en
Version v2.0.0 updated 28 August 2018

<img width="1156" alt="915 - blank comment triggers error - fixed" src="https://user-images.githubusercontent.com/3064318/44697280-abb20680-aa40-11e8-966b-19994ae4ae3c.png">
