### ISSUE TITLE
Get sample files of ESD and Registrar Feed

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/laevigata#94]
- [ ] Get sample files from the Emory dev who just returned from Colombia

**Comment by shanitajohn** [comment]
Data dictionary for ESD is in Box, DCE will review.

**Comment by alexBLR** [comment]
https://github.com/emory-libraries/ETD/blob/master/src/app/models/esdPerson.php#L39-L66

**Comment by mark-dce** [comment]
ESD Data dictionary is on box https://app.box.com/files/0/f/23152405805/1/f_158423744275

**Comment by alexBLR** [comment]
Registrar Feed: https://github.com/emory-libraries/ETD/blob/master/src/scripts/publish.php#L320-L333

**Comment by bess** [comment]
It looks like these are the code that fetch the registrar feed. I thought we were looking for an actual sample of what the data looks like?

**Comment by acozine** [comment]
A sanitized sample of what the data looks like after retrieval would help us test the two operations separately: first using the data, then retrieving the data.

**Comment by shanitajohn** [comment]
Tiffany - looking into getting sample data for ESD and Registrar feed, sanitized, or live data.

**Comment by rosy1280** [comment]
I've started to think that we may be able to get all the information we need from Shibboleth -- perhaps utilizing Emory Shared Data was a work around because we were using LDAP previously.  @alexBLR and @rotated8 can one of you fill out the Shibboleth form and include the fields that we identified we need from Emory Shared Data as the attributes we would like passed to us upon log in.  Then submit a ticket to the IdM group via Service Now.  @tmiles2 can help with the ticket writing if you need it.  Let me know if this isn't clear.

**Comment by bess** [comment]
That would be great, and would tremendously simplify things. Good idea!

**Comment by mark-dce** [comment]
@rotated8 and @bnash108 to review existing feeds and determine if there are any fields we can weed out (the fewer fields the better in terms of passing security reviews ;) )

**Comment by alexBLR** [comment]
The Registrar feed that we pass https://emory.box.com/s/01u2086ohia42qvy3hzr25h0vaywo5ks

Would that work?

**Comment by shanitajohn** [comment]
Needs to be rewritten
