### ISSUE TITLE
Student uploads from Box generating "invalid" links

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/laevigata#960]
This ticket references the issue in Freshdesk ticket #42
https://curationexperts.freshdesk.com/helpdesk/tickets/42

**TASK**
- [ ] Change the length of time on the file expiration setting in browse_everything

**Comment by no-reply** [comment]
The generated Box links we are persisting to the DB are valid for 15 minutes. We have taken steps to ensure that all jobs are processed within this window.

Unfortunately, we don't have control over this expiration time. Box also returns (but `browse_everything` discards) an `access_key` and a `renewal_key`. These are valid for 60 minutes and 60 days, respectively. A larger rework of `BrowseEverything` and `Hyrax` would be needed to take advantage of these keys.

**Comment by bess** [comment]
Since we can't change the expiration time of browse-everything, here's what we did:

1) Prioritize remote file attachment jobs
2) Monitor the file attachment queues and get alerted if they are falling behind
3) Alert students if their file did not attach so they can re-submit it
4) Set up sidekiq as a system service so if the machine reboots or sidekiq crashes it will get restarted
